[pytest]
addopts= --base-url http://127.0.0.1:8000 --device "iPhone 11" --browser=firefox --junitxml=junit-report.xml --alluredir report/
#base-url = http://127.0.0.1:8000
headless=False

# logs
log_cli=True
log_file=test.log
log_file_level=INFO

markers =
    test_id: marks tests for reporting
